<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <JavaSdkDirectory>C:\Program Files\Microsoft\jdk-21.0.9.10-hotspot</JavaSdkDirectory>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <Nullable>enable</Nullable>
    
    <ApplicationId>com.CompanyName.MobileCDInventory</ApplicationId>
    <ApplicationVersion>5</ApplicationVersion>
    <ApplicationDisplayVersion>1.4</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>

    <Deterministic>false</Deterministic>
    <AssemblyVersion>1.3.0.0</AssemblyVersion>

    <!-- Suppress the Android 16KB page size warning (XA0141) until Avalonia fixes it -->
    <NoWarn>$(NoWarn);XA0141</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <AndroidResource Include="Icon.png">
      <Link>Resources\drawable\Icon.png</Link>
    </AndroidResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" />
    <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" />

    <!-- Explicit package references -->
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Android" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MobileCDInventory\MobileCDInventory.csproj" />
  </ItemGroup>
</Project>